# 1112_DS_Lab3  資料聚合及遮罩應用於股價分析

# Aggregations(聚合函數): Min, Max, and Everything In Between
Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).
** Most texts are released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT).

In [1]:
import numpy as np
A = np.random.random(100)
A

array([0.57503223, 0.35790832, 0.57022331, 0.37519164, 0.13872586,
       0.36637872, 0.84011711, 0.75480612, 0.50882206, 0.59189577,
       0.86533758, 0.25383517, 0.32009339, 0.25302047, 0.58268506,
       0.57214828, 0.12178331, 0.06482749, 0.92016776, 0.45424391,
       0.02093028, 0.95701179, 0.07194664, 0.6492841 , 0.18138818,
       0.68577577, 0.79147339, 0.97330354, 0.89312401, 0.49367273,
       0.20886066, 0.607066  , 0.34850562, 0.29601821, 0.29695936,
       0.22272345, 0.45540309, 0.03832664, 0.95777441, 0.28208585,
       0.85640483, 0.02986444, 0.7898094 , 0.44797003, 0.25220351,
       0.68449535, 0.89803815, 0.84003347, 0.0758863 , 0.82614107,
       0.37879826, 0.63278706, 0.8229434 , 0.8229861 , 0.52487371,
       0.98241982, 0.72683446, 0.10156124, 0.29994295, 0.77401544,
       0.56118969, 0.44345356, 0.18838095, 0.35857975, 0.19157366,
       0.0975191 , 0.3608573 , 0.97271751, 0.00688703, 0.52490492,
       0.03868259, 0.36246016, 0.05786425, 0.65494419, 0.30823

In [3]:
np.sum(A)
%timeit sum(A)
%timeit np.sum(A)

14.1 µs ± 418 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.83 µs ± 28 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
big_array = np.random.rand(1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

128 µs ± 3.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.37 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
np.min(big_array), np.max(big_array)  # 比較快

(0.00036471890996137013, 0.9995631998003469)

In [6]:
M = np.random.random((3, 4))
print(M)

[[0.81497177 0.88009378 0.83560684 0.37887626]
 [0.24939376 0.9157718  0.25988084 0.53962103]
 [0.62332105 0.04087657 0.0598424  0.86844743]]


In [9]:
print(sum(sum(M)))

6.4667035208570915


In [10]:
M.sum()

6.4667035208570915

## Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. 
For example, we can find the minimum value within each column by specifying axis=0. The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned. So specifying axis=0 means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

![AXIS範例](axis.jpg)

In [11]:
M.sum(axis=0)

array([1.68768658, 1.83674214, 1.15533008, 1.78694472])

In [12]:
M.sum(axis=1)

array([2.90954864, 1.96466743, 1.59248746])

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |



In [13]:
import pandas as pd
import numpy as np
import requests

In [15]:
date = "20230320"
url = f'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date={date}&type=ALLBUT0999'
response = requests.get(url)
response_json = response.json()
stockdata = pd.DataFrame(response_json['data9'], columns=response_json['fields9'])
origin = stockdata.copy()
stockdata.head()

證券代號      證券名稱       成交股數    成交筆數         成交金額     開盤價     最高價     最低價  \
0  0050    元大台灣50  7,527,505  12,258  889,553,151  118.95  119.05  117.85   
1  0051   元大中型100     54,091     161    3,004,569   55.30   55.75   55.30   
2  0052      富邦科技    182,010     301   19,229,478  106.10  106.15  105.40   
3  0053      元大電子     14,110   1,010      831,554   58.85   59.05   58.85   
4  0055  元大MSCI金融    258,280     479    5,500,399   21.44   21.44   21.21   

      收盤價                      漲跌(+/-)  漲跌價差  最後揭示買價 最後揭示買量  最後揭示賣價 最後揭示賣量  \
0  118.10  <p style= color:green>-</p>  0.85  118.05      8  118.10    290   
1   55.60    <p style= color:red>+</p>  0.20   55.50      2   55.70      3   
2  105.65  <p style= color:green>-</p>  0.60  105.65     21  105.70      1   
3   58.95                     <p> </p>  0.00   58.60     36   59.05      2   
4   21.26  <p style= color:green>-</p>  0.14   21.28      3   21.31      9   

    本益比  
0  0.00  
1  0.00  
2  0.00  
3  0.00  
4  0.00

In [17]:
dayprice = np.array(stockdata['收盤價'])   #也可以這樣寫  dayprice = np.array(stockdata.收盤價)
print(dayprice)

['118.10' '55.60' '105.65' ... '11.90' '25.50' '99.50']


In [24]:
a = np.array(stockdata.收盤價[0:9])
print(a)

['118.10' '55.60' '105.65' '58.95' '21.26' '27.76' '85.70' '18.85' '56.90']


In [26]:
print(len(a))
print(type(a))

9
<class 'numpy.ndarray'>


In [27]:
a= a.astype(np.float)
print(a)

[118.1   55.6  105.65  58.95  21.26  27.76  85.7   18.85  56.9 ]


In [28]:
print(a.mean())

60.974444444444444


In [29]:
print("Mean 收盤價:", a.mean())
print("Standard 收盤價:", a.std())
print("Minimum 收盤價:    ", a.min())
print("Maximum 收盤價:    ", a.max())
print("25th percentile:   ", np.percentile(a, 25))
print("Median:            ",  np.median(a))
print("75th percentile:   ", np.percentile(a, 75))

Mean 收盤價: 60.974444444444444
Standard 收盤價: 33.95270701402536
Minimum 收盤價:     18.85
Maximum 收盤價:     118.1
25th percentile:    27.76
Median:             56.9
75th percentile:    85.7


In [31]:
print("Mean 收盤價:", dayprice.mean())
print("Standard 收盤價:", dayprice.std())
print("Minimum 收盤價:    ", dayprice.min())
print("Maximum 收盤價:    ", dayprice.max())
print("25th percentile:   ", dayprice.percentile(heights, 25))
print("Median:            ", dayprice.median(heights))
print("75th percentile:   ", dayprice.percentile(heights, 75))

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [33]:
print(dayprice[0:40])

['118.10' '55.60' '105.65' '58.95' '21.26' '27.76' '85.70' '18.85' '56.90'
 '77.45' '31.55' '30.01' '24.66' '68.20' '--' '110.15' '5.38' '37.29'
 '4.53' '25.12' '21.15' '6.93' '14.68' '9.59' '12.64' '27.81' '9.65'
 '14.07' '14.66' '--' '25.75' '37.15' '50.55' '7.42' '12.16' '8.80'
 '27.80' '38.63' '8.47' '26.35']


In [34]:
b= np.array(stockdata.收盤價[0:40])

In [37]:
print(b)
print(b.size)

['118.10' '55.60' '105.65' '58.95' '21.26' '27.76' '85.70' '18.85' '56.90'
 '77.45' '31.55' '30.01' '24.66' '68.20' '--' '110.15' '5.38' '37.29'
 '4.53' '25.12' '21.15' '6.93' '14.68' '9.59' '12.64' '27.81' '9.65'
 '14.07' '14.66' '--' '25.75' '37.15' '50.55' '7.42' '12.16' '8.80'
 '27.80' '38.63' '8.47' '26.35']
40


In [38]:
b= b.astype(np.float)

ValueError: could not convert string to float: '--'

In [40]:
b_new=(b!='--')
print(b_new)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True]


In [41]:
b1= b[b_new].astype(np.float)

In [42]:
print(b1)
print(b1.size)

[118.1   55.6  105.65  58.95  21.26  27.76  85.7   18.85  56.9   77.45
  31.55  30.01  24.66  68.2  110.15   5.38  37.29   4.53  25.12  21.15
   6.93  14.68   9.59  12.64  27.81   9.65  14.07  14.66  25.75  37.15
  50.55   7.42  12.16   8.8   27.8   38.63   8.47  26.35]
38


# Comparisons, Masks, and Boolean Logic

## Comparison Operators as ufuncs
The result of these comparison operators is always an array with a Boolean data type. All six of the standard comparison operations are available:

In [43]:
x = np.array([1, 2, 3, 4, 5])

In [44]:
x < 3  # less than

array([ True,  True, False, False, False])

In [45]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [46]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [47]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [48]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [50]:
x == 3  # equal

array([False, False,  True, False, False])

In [51]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

## Working with Boolean Arrays

Given a Boolean array, there are a host of useful operations you can do.
We'll work with ``x``, the two-dimensional array we created earlier.

In [52]:
x=np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
# how many values less than 6?
np.count_nonzero(x < 6)

6

In [55]:
# how many values less than 6 in each row?
np.sum(x<6 , axis=1)

array([4, 2, 0])

In [56]:
# are there any values greater than 8?
np.any(x > 8)

True

In [57]:
# are all values less than 12?
np.all(x < 12)

True

In [58]:
np.where(x==7)

(array([1], dtype=int64), array([3], dtype=int64))

## 當日股價分析

In [59]:
dayprice = np.array(stockdata.收盤價)

In [60]:
dayprice_yes=(dayprice!='--')
print(dayprice_yes[0:40])

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True]


In [62]:
dayprice= dayprice[dayprice_yes].astype(np.float)

ValueError: could not convert string to float: '1,145.00'

In [63]:
np.where(dayprice=='1,145.00')

(array([316], dtype=int64),)

In [65]:
dayprice[316]

'1,145.00'

In [66]:
dayprice[316]='1145'

In [71]:
dayprice= dayprice[dayprice_yes].astype(np.float)

ValueError: could not convert string to float: '2,230.00'

In [72]:
np.where(dayprice=='2,230.00')

(array([707], dtype=int64),)

In [73]:
dayprice[707]='2230'

In [76]:
dayprice= dayprice[dayprice_yes].astype(np.float)

ValueError: could not convert string to float: '1,170.00'

In [77]:
np.where(dayprice=='1,170.00')

(array([787], dtype=int64),)

In [78]:
dayprice[787]='1170'

In [88]:
dayprice= dayprice[dayprice_yes].astype(np.float)

In [86]:
np.where(dayprice=='1,680.00')

(array([1008], dtype=int64),)

In [87]:
dayprice[1008]='1680'

In [89]:
print("Mean 當日收盤價:", dayprice.mean())
print("Standard 當日收盤價:", dayprice.std())
print("Minimum 當日收盤價:    ", dayprice.min())
print("Maximum 當日收盤價:    ", dayprice.max())
print("25th percentile:   ", np.percentile(dayprice, 25))
print("Median:            ", np.median(dayprice))
print("75th percentile:   ", np.percentile(dayprice, 75))

Mean 當日收盤價: 66.0662564102564
Standard 當日收盤價: 135.84737531510365
Minimum 當日收盤價:     1.2
Maximum 當日收盤價:     2230.0
25th percentile:    17.84
Median:             33.0
75th percentile:    65.125


# 作業二(Due 3/28): 請用 "date = "2023/03/21" 分析股市的開盤價和收盤價的平均值和標準差。